from typing import overload
from enum import IntEnum

class PycpType(IntEnum):
	PYCP_TP_OBJECT: int
	PYCP_TP_NONE: int
	PYCP_TP_INTEGER: int
	PYCP_TP_STRING: int
	PYCP_TP_FUNCTION: int

class PycpObject:
	def __init__(self) -> None: ...
	
	@property
	def type(self) -> PycpType: ...
	
	def __integer__(self) -> PycpObject: ...
	def __string__(self) -> PycpObject: ...
	def __negation__(self) -> PycpObject: ...
	def __call__(self, args: PycpObject) -> PycpObject: ...
	def __addition__(self, other: PycpObject) -> PycpObject: ...
	def __subtraction__(self, other: PycpObject) -> PycpObject: ...
	def __multiplication__(self, other: PycpObject) -> PycpObject: ...
	def __division__(self, other: PycpObject) -> PycpObject: ...

class PycpInteger(PycpObject):
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, value: int) -> None: ...
	@overload
	def __init__(self, value: str) -> None: ...
	@overload
	def __init__(self, value: PycpInteger) -> None: ...
	@overload
	def __init__(self, value: PycpObject) -> None: ...
	
	def get_value(self) -> int: ...
	
	def __integer__(self) -> PycpObject: ...
	def __string__(self) -> PycpObject: ...
	def __negation__(self) -> PycpObject: ...
	def __addition__(self, other: PycpObject) -> PycpObject: ...
	def __subtraction__(self, other: PycpObject) -> PycpObject: ...
	def __multiplication__(self, other: PycpObject) -> PycpObject: ...
	def __division__(self, other: PycpObject) -> PycpObject: ...

class PycpString(PycpObject):
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, value: str) -> None: ...
	@overload
	def __init__(self, value: PycpString) -> None: ...
	@overload
	def __init__(self, value: PycpObject) -> None: ...
	
	def get_value(self) -> str: ...
	
	def __integer__(self) -> PycpObject: ...
	def __string__(self) -> PycpObject: ...
	def __addition__(self, other: PycpObject) -> PycpObject: ...
	def __multiplication__(self, other: PycpObject) -> PycpObject: ...

class PycpNone(PycpObject):
	def __init__(self) -> None: ...
	
	@property
	def instance(self) -> PycpNone: ...
	
	def __integer__(self) -> PycpObject: ...
	def __string__(self) -> PycpObject: ...

class PycpFunction(PycpObject):
	@overload
	def __init__(self, name: str) -> None: ...
	@overload
	def __init__(self, name: str, func: object) -> None: ...  # func is a C++ function
	
	def __call__(self, args: PycpObject) -> PycpObject: ...
	def get_name(self) -> str: ...
	
class PycpBuiltinFunction:
	@staticmethod
	def print(arg: PycpObject) -> PycpNone: ...