#include "aot/PycpCMakeGenerator.hpp"

#include <sstream>

namespace Pycp::AOT {

const CMakeGenerator kCMakeGenerator;

// 静态初始化阶段自注册：委托全局实例的地址，确保本生成器纳入注册表。
namespace {
const bool kRegistered = []() {
	RegisterGenerator(&kCMakeGenerator);
	return true;
}();
} // anonymous namespace

namespace {

// 转义，使其在 CMake 字符串字面量中安全（处理反斜杠与引号）。
std::string cmake_escape(const std::string& s) {
	std::string out;
	out.reserve(s.size() + 4);
	for (char c : s) {
		if (c == '\\') out += "\\\\";
		else if (c == '"') out += "\\\"";
		else out += c;
	}
	return out;
}

} // anonymous namespace

std::string CMakeGenerator::Generate(const ProjectSpec& spec) const {
	const SdkInfo& sdk = spec.sdk;
	std::ostringstream os;

	// 文件头：注明生成来源与版本，便于追溯。
	os << "# Generated by Pycp AOT (emit-cpp) v"
	   << cmake_escape(spec.pycp_version) << "\n";
	os << "# Source entry : " << cmake_escape(spec.source_pycp) << "\n";
	os << "# Do not edit by hand; re-run: pycp --emit-cpp <entry>.pycp\n\n";

	os << "cmake_minimum_required(VERSION 3.15)\n";
	os << "project(" << spec.name << " LANGUAGES CXX)\n\n";

	// SDK 根目录：生成时写入绝对路径；换机器用 -DPYCP_DIST=<path> 覆盖。
	os << "# Pycp 运行时 SDK 根目录（生成时写入的绝对路径；换机器用 "
	      "-DPYCP_DIST=<path> 覆盖）\n";
	os << "set(PYCP_DIST \"" << cmake_escape(sdk.root) << "\" CACHE PATH "
	      "\"Pycp runtime SDK root\")\n\n";

	os << "set(CMAKE_CXX_STANDARD 17)\n";
	os << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
	os << "set(CMAKE_CXX_EXTENSIONS OFF)\n";
	os << "if(NOT CMAKE_BUILD_TYPE)\n";
	os << "    set(CMAKE_BUILD_TYPE Release)\n";
	os << "endif()\n\n";

	// SDK 缺失时给出可操作错误，而非晦涩的 "cannot find -lPycpRuntime"。
	os << "# SDK 缺失时给出可操作的错误，而非晦涩的 \"cannot find -lPycpRuntime\"\n";
	os << "if(NOT EXISTS \"${PYCP_DIST}/include/PycpABI.hpp\")\n";
	os << "    message(FATAL_ERROR\n";
	os << "        \"Pycp SDK not found at: ${PYCP_DIST}\\n\"\n";
	os << "        \"请指定正确的 SDK 路径：cmake -S . -B build "
	      "-DPYCP_DIST=<pycp 的 build/dist>\")\n";
	os << "endif()\n\n";

	// 源文件显式列出（不用 GLOB：新增文件不会触发 CMake 重新配置）。
	os << "# 源文件显式列出（不用 GLOB：新增文件不会触发 CMake 重新配置）\n";
	os << "add_executable(" << spec.name << "\n";
	for (const auto& kv : spec.sources) {
		os << "    " << kv.first << "\n";
	}
	os << ")\n\n";

	os << "target_include_directories(" << spec.name
	   << " PRIVATE \"${PYCP_DIST}/include\")\n";
	os << "target_link_directories(" << spec.name
	   << " PRIVATE \"${PYCP_DIST}/lib\")\n\n";

	// 必须动态链接：stdlib 扩展（io.so 等）同样链接 libPycpRuntime，
	// 静态链接会让进程内出现两份运行时状态（GC 池 / 小整数池 / 句柄缓存）。
	os << "# 必须动态链接：stdlib 扩展（io.so 等）同样链接 libPycpRuntime，\n";
	os << "# 静态链接会让进程内出现两份运行时状态（GC 池 / 小整数池 / 句柄缓存）。\n";
	os << "target_link_libraries(" << spec.name << " PRIVATE PycpRuntime)\n\n";

	// rpath：让 exe 在任何目录都能找到同级 lib/ 下的运行时库。
	os << "# rpath：让 exe 在任何目录都能找到同级 lib/ 下的运行时库\n";
	os << "set_target_properties(" << spec.name << " PROPERTIES\n";
	os << "    BUILD_RPATH   \"${PYCP_DIST}/lib;$ORIGIN/lib;$ORIGIN\"\n";
	os << "    INSTALL_RPATH \"$ORIGIN/lib;$ORIGIN\"\n";
	os << ")\n\n";

	// Linux/macOS：导出主程序符号，使 import 的「进程内符号」查找
	// （dlsym(RTLD_DEFAULT, "PycpModule_xxx")）能命中链接进本程序的模块。
	os << "# Linux/macOS：导出主程序符号，使 import 的「进程内符号」查找\n";
	os << "# （dlsym(RTLD_DEFAULT, \"PycpModule_xxx\")）能命中链接进本程序的模块。\n";
	os << "if(UNIX AND NOT APPLE)\n";
	os << "    target_link_options(" << spec.name << " PRIVATE -rdynamic)\n";
	os << "endif()\n\n";

	// 运行期部署：import io 等按「exe 同级 stdlib/」查找原生扩展，
	// 且 io.so 自身 rpath 指向 $ORIGIN/../lib，故 lib/ 必须一并复制。
	os << "# 运行期部署：import io 等按「exe 同级 stdlib/」查找原生扩展，\n";
	os << "# 且 io.so 自身 rpath 指向 $ORIGIN/../lib，故 lib/ 必须一并复制。\n";
	os << "add_custom_command(TARGET " << spec.name << " POST_BUILD\n";
	os << "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
	os << "            \"${PYCP_DIST}/stdlib\" $<TARGET_FILE_DIR:" << spec.name
	   << ">/stdlib\n";
	os << "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
	os << "            \"${PYCP_DIST}/lib\" $<TARGET_FILE_DIR:" << spec.name
	   << ">/lib\n";
	os << ")\n\n";

	// Windows：加载 DLL 只搜 exe 同级目录、不搜 lib/，故运行时 DLL 额外放一份。
	os << "# Windows：加载 DLL 只搜 exe 同级目录、不搜 lib/，故运行时 DLL 额外放一份。\n";
	os << "if(WIN32)\n";
	os << "    add_custom_command(TARGET " << spec.name << " POST_BUILD\n";
	os << "        COMMAND ${CMAKE_COMMAND} -E copy_if_different\n";
	os << "                \"${PYCP_DIST}/PycpRuntime.dll\" $<TARGET_FILE_DIR:"
	   << spec.name << ">/\n";
	os << "    )\n";
	os << "endif()\n";

	return os.str();
}

} // namespace Pycp::AOT
