#include "aot/PycpCMakeGenerator.hpp"

#include "PycpConfig.hpp" // AOT_ENTRY_CPP_FILENAME

#include <algorithm>
#include <map>
#include <set>
#include <sstream>
#include <vector>

namespace Pycp::AOT {

const CMakeGenerator kCMakeGenerator;

// 静态初始化阶段自注册：委托全局实例的地址，确保本生成器纳入注册表。
namespace {
const bool kRegistered = []() {
	RegisterGenerator(&kCMakeGenerator);
	return true;
}();
} // anonymous namespace

namespace {

// 转义，使其在 CMake 字符串字面量中安全（处理反斜杠与引号）。
std::string cmake_escape(const std::string& s) {
	std::string out;
	out.reserve(s.size() + 4);
	for (char c : s) {
		if (c == '\\') out += "\\\\";
		else if (c == '"') out += "\\\"";
		else out += c;
	}
	return out;
}

// 取路径最后一段（文件名）；无分隔符时返回原串。
// 用于把 SdkInfo::root_dll（绝对路径）转成写入 CMake 的候选文件名。
std::string base_name(const std::string& path) {
	const std::size_t pos = path.find_last_of("/\\");
	return (pos == std::string::npos) ? path : path.substr(pos + 1);
}

// 路径安全化：分隔符统一为 '/'，再转义引号。
//
// 必须统一分隔符：写入 CMake 的绝对路径若含 '\'，在 target_link_libraries
// 这类「原样进入 Makefile 链接命令行」的位置会被 make 当成转义符吞掉，
// MinGW 下表现为 ld "cannot find D:DesktopPycpbuild/dist/lib/..."。
// Windows 接受 '/' 作为路径分隔符，故统一后两端都安全。
std::string cmake_path(const std::string& s) {
	std::string out;
	out.reserve(s.size() + 4);
	for (char c : s) {
		if (c == '\\') out += '/';
		else if (c == '"') out += "\\\"";
		else out += c;
	}
	return out;
}

// 依赖模块的 CMake target 名。入口模块恒编进主程序（target 名即 project 名），
// 且不出现在 spec.modules 中，故二者不可能重名。
std::string module_target(const std::string& name) {
	return "pycp_mod_" + name;
}

// 计算某链接目标（入口或模块）的「静态依赖闭包」：需要链入该目标的静态
// 模块名集合（不含 start 自身）。
//
// 从直接依赖出发做深度优先遍历：
//   - 遇 kShared 依赖即停止下钻：其符号在独立 DLL 中，运行期按名 dlopen
//     加载，不参与链接（对其 extern 引用会制造无法解析的外部符号）。
//   - 沿 kStatic 依赖继续下钻，收集全部传递静态依赖——静态库只按符号
//     拉取成员，故依赖闭包内的每个静态库都必须出现在链接行上。
//   - visited 去重，循环 import（a <-> b）不会无限递归。
std::set<std::string> StaticClosure(
	const std::string& start,
	const std::vector<ModuleTarget>& modules,
	const std::map<std::string, std::vector<std::string>>& deps) {
	std::map<std::string, ModuleKind> kinds;
	for (const ModuleTarget& mt : modules) kinds[mt.name] = mt.kind;

	std::set<std::string> out;
	std::set<std::string> visited;
	std::vector<std::string> stack;

	auto push_deps = [&](const std::string& n) {
		auto dit = deps.find(n);
		if (dit == deps.end()) return;
		for (const std::string& d : dit->second) stack.push_back(d);
	};

	push_deps(start);
	while (!stack.empty()) {
		const std::string n = stack.back();
		stack.pop_back();
		if (!visited.insert(n).second) continue;
		auto kit = kinds.find(n);
		if (kit == kinds.end()) continue;                 // 非本批模块（stdlib 扩展）
		if (kit->second != ModuleKind::kStatic) continue; // 动态模块：运行期加载
		out.insert(n);
		push_deps(n);
	}
	return out;
}

} // anonymous namespace

std::string CMakeGenerator::Generate(const ProjectSpec& spec) const {
	const SdkInfo& sdk = spec.sdk;
	const bool rt_shared = (spec.runtime_link == LinkMode::kShared);
	const std::string& exe = spec.name;

	// 依赖模块按形态分类（入口恒在主程序 exe 内，不在此列）。
	std::vector<const ModuleTarget*> mod_static;
	std::vector<const ModuleTarget*> mod_shared;
	for (const ModuleTarget& mt : spec.modules) {
		if (mt.kind == ModuleKind::kShared) mod_shared.push_back(&mt);
		else mod_static.push_back(&mt);
	}

	// 模块名 -> 直接依赖（含入口），供静态依赖闭包遍历使用。
	std::map<std::string, std::vector<std::string>> deps;
	for (const ModuleTarget& mt : spec.modules) deps[mt.name] = mt.deps;
	deps[exe] = spec.entry_deps;

	// 各链接目标的静态依赖闭包：主程序与每个模块各一份。
	std::map<std::string, std::set<std::string>> closure;
	closure[exe] = StaticClosure(exe, spec.modules, deps);
	for (const ModuleTarget& mt : spec.modules) {
		closure[mt.name] = StaticClosure(mt.name, spec.modules, deps);
	}

	std::ostringstream os;

	// 文件头：注明生成来源与版本、关键形态，便于追溯。
	os << "# Generated by Pycp AOT (emit-cpp) v"
	   << cmake_escape(spec.pycp_version) << "\n";
	os << "# Source entry : " << cmake_escape(spec.source_pycp) << "\n";
	os << "# Runtime link : "
	   << (rt_shared ? "shared (libPycpRuntime)" : "static (libPycpRuntime.a)")
	   << "\n";
	os << "# Module kinds : " << mod_static.size() << " static, "
	   << mod_shared.size() << " shared (one CMake target each)\n";
	// 逐模块列出形态与决策原因（--compile-modules= / --compile-module:X= /
	// forced shared），形态不符合预期时可据此回溯。
	for (const ModuleTarget& mt : spec.modules) {
		os << "#   " << ((mt.kind == ModuleKind::kShared) ? "shared" : "static")
		   << "  " << mt.name << "  ("
		   << (mt.reason.empty() ? std::string("<default>") : mt.reason) << ")\n";
	}
	os << "# Builtin ext   : " << spec.builtin_static.size()
	   << " static (linked in), " << spec.builtin_shared.size()
	   << " shared (loaded from stdlib/)\n";
	os << "# Do not edit by hand; re-run: pycp --emit-cpp <entry>.pycp\n\n";

	os << "cmake_minimum_required(VERSION 3.15)\n";
	os << "project(" << exe << " LANGUAGES CXX)\n\n";

	// SDK 根目录：生成时写入绝对路径；换机器用 -DPYCP_DIST=<path> 覆盖。
	os << "# Pycp 运行时 SDK 根目录（生成时写入的绝对路径；换机器用 "
	      "-DPYCP_DIST=<path> 覆盖）\n";
	os << "set(PYCP_DIST \"" << cmake_path(sdk.root) << "\" CACHE PATH "
	      "\"Pycp runtime SDK root\")\n\n";

	os << "set(CMAKE_CXX_STANDARD 17)\n";
	os << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
	os << "set(CMAKE_CXX_EXTENSIONS OFF)\n";
	os << "if(NOT CMAKE_BUILD_TYPE)\n";
	os << "    set(CMAKE_BUILD_TYPE Release)\n";
	os << "endif()\n\n";

	// SDK 缺失时给出可操作错误，而非晦涩的 "cannot find -lPycpRuntime"。
	os << "# SDK 缺失时给出可操作的错误，而非晦涩的 \"cannot find -lPycpRuntime\"\n";
	os << "if(NOT EXISTS \"${PYCP_DIST}/include/PycpABI.hpp\")\n";
	os << "    message(FATAL_ERROR\n";
	os << "        \"Pycp SDK not found at: ${PYCP_DIST}\\n\"\n";
	os << "        \"请指定正确的 SDK 路径：cmake -S . -B build "
	      "-DPYCP_DIST=<pycp 的 build/dist>\")\n";
	os << "endif()\n\n";

	// ---- 入口源与辅助源（注册桩等）----
	// 入口 .gen.cpp 固定名（AOT_ENTRY_CPP_FILENAME）；aux 桩编进主程序。
	os << "# 入口模块与辅助源（注册/拉入桩）编进主程序可执行文件\n";
	os << "set(PYCP_ENTRY_SRC \"" << Pycp::AOT_ENTRY_CPP_FILENAME << "\")\n";
	if (spec.aux_sources.empty()) {
		os << "set(PYCP_AUX_SRCS)\n";
	} else {
		os << "set(PYCP_AUX_SRCS\n";
		for (const std::string& a : spec.aux_sources) os << "    " << a << "\n";
		os << ")\n";
	}
	os << "\n";

	// ---- 目标：主程序 ----
	os << "# ---- 主程序（入口模块 + 辅助源）----\n";
	os << "add_executable(" << exe << " ${PYCP_ENTRY_SRC} ${PYCP_AUX_SRCS})\n\n";

	// ---- 目标：依赖模块（逐模块一个 target，形态由 ModulePlan 决定）----
	// 静态模块各自一个归档（lib<name>.a），动态模块各自一个 DLL/SO。
	// 逐模块独立后，静态库之间用 target_link_libraries(... PUBLIC ...) 传播
	// 依赖闭包；CMake 允许 STATIC 库之间存在依赖环，会在链接行重复整个
	// 连通分量，故模块间循环 import 依然成立。
	if (!spec.modules.empty()) {
		os << "# ---- 依赖模块：逐模块一个 target（static -> 归档，"
		      "shared -> DLL）----\n";
		for (const ModuleTarget& mt : spec.modules) {
			const std::string t = module_target(mt.name);
			const bool is_shared = (mt.kind == ModuleKind::kShared);
			os << "# " << mt.name << " (" << (is_shared ? "shared" : "static")
			   << (mt.reason.empty() ? std::string() : ", " + mt.reason) << ")\n";
			os << "add_library(" << t << " " << (is_shared ? "SHARED" : "STATIC")
			   << " " << mt.source_file << ")\n";
			os << "set_target_properties(" << t << " PROPERTIES\n";
			// 输出名直接取模块名：静态库得 lib<name>.a（MSVC 为 <name>.lib），
			// 动态库去掉默认前缀后得 <name>.so/.dll（运行期按名查找）。
			os << "    OUTPUT_NAME \"" << mt.name << "\"\n";
			if (is_shared) {
				os << "    PREFIX \"\"\n";
			} else {
				// 静态模块可能被链进动态模块 DLL，必须编译为位置无关代码，
				// 否则 MinGW/Linux 下链接 DLL 时报重定位错误。
				os << "    POSITION_INDEPENDENT_CODE ON\n";
			}
			os << ")\n";
		}
		os << "\n";
	}

	// ---- 各 target 的 include/link 目录（统一段）----
	auto emit_common_dirs = [&](const std::string& t) {
		os << "target_include_directories(" << t
		   << " PRIVATE \"${PYCP_DIST}/include\")\n";
		os << "target_link_directories(" << t
		   << " PRIVATE \"${PYCP_DIST}/lib\")\n";
	};
	emit_common_dirs(exe);
	for (const ModuleTarget& mt : spec.modules) {
		emit_common_dirs(module_target(mt.name));
	}
	os << "\n";

	// ---- 编译定义 ----
	// 静态运行时（全镜像无 DLL）：所有参与链接的 TU 取消 __declspec(dllimport)。
	// 动态模块 DLL：定义 PYCP_BUILDING_MODULE 以 dllexport 自身入口。
	if (!rt_shared) {
		os << "target_compile_definitions(" << exe << " PRIVATE PYCP_STATIC)\n";
		for (const ModuleTarget* mt : mod_static) {
			os << "target_compile_definitions(" << module_target(mt->name)
			   << " PRIVATE PYCP_STATIC)\n";
		}
		os << "\n";
	}
	for (const ModuleTarget* mt : mod_shared) {
		os << "target_compile_definitions(" << module_target(mt->name)
		   << " PRIVATE PYCP_BUILDING_MODULE)\n";
	}
	if (!mod_shared.empty()) os << "\n";

	// ---- 链接关系 ----
	os << "# ---- 链接 ----\n";
	if (!closure[exe].empty()) {
		os << "# 主程序链接其静态依赖闭包（链接器按符号拉取所需成员）。\n";
	}
	os << "target_link_libraries(" << exe << " PRIVATE\n";
	for (const std::string& n : closure[exe]) {
		os << "    " << module_target(n) << "\n";
	}
	// 静态链入的内置扩展（--compile-module:io=static 等）：注册桩引用了
	// PycpModule_<name>，必须显式链接对应静态库才能解析。这与运行时形态
	// 无关——runtime 为 shared 时同样需要，否则报 undefined reference。
	if (!spec.builtin_static_lib_paths.empty()) {
		os << "    # 静态链入的内置扩展（绝对路径，避免 MinGW 选中同目录的\n";
		os << "    # DLL 导入库）；须排在运行时之前，GNU ld 按左到右解析。\n";
		for (const std::string& lib : spec.builtin_static_lib_paths) {
			os << "    \"" << cmake_path(lib) << "\"\n";
		}
	}
	if (rt_shared) {
		// 共享运行时：主程序与 stdlib 扩展统一链接同一份 libPycpRuntime，
		// 保证全进程只有一份运行时状态（GC 池 / 小整数池 / 句柄缓存）。
		os << "    PycpRuntime\n";
	} else {
		os << "    # 静态运行时（绝对路径，避免 MinGW 选中同目录的 DLL 导入库\n";
		os << "    # libPycpRuntime.dll.a）\n";
		os << "    \"" << cmake_path(sdk.static_runtime) << "\"\n";
	}
	os << ")\n\n";

	// 静态模块：PUBLIC 传播自身的静态依赖闭包，使最终链接目标（主程序 /
	// 动态模块 DLL）能解析出全部所需符号。静态库本身不参与链接，此处仅
	// 记录依赖；CMake 允许 STATIC 库之间成环，故循环 import 亦可收敛。
	for (const ModuleTarget* mt : mod_static) {
		const std::set<std::string>& cl = closure.at(mt->name);
		if (cl.empty()) continue;
		os << "target_link_libraries(" << module_target(mt->name) << " PUBLIC\n";
		for (const std::string& n : cl) {
			os << "    " << module_target(n) << "\n";
		}
		os << ")\n";
	}
	if (!mod_static.empty()) os << "\n";

	// 动态模块：链接共享运行时（runtime 为 static 时不允许存在动态模块）
	// 与自身的静态依赖闭包——静态依赖被链进本 DLL，不会复制到其它目标。
	for (const ModuleTarget* mt : mod_shared) {
		const std::string t = module_target(mt->name);
		os << "target_link_libraries(" << t << " PRIVATE\n";
		for (const std::string& n : closure.at(mt->name)) {
			os << "    " << module_target(n) << "\n";
		}
		os << "    PycpRuntime\n";
		os << ")\n";
		// DLL 自己的 rpath：运行期需要定位 libPycpRuntime（若部署时放在
		// 别处）以及自身可能的静态依赖（不适用，static 依赖已链入自身）。
		os << "set_target_properties(" << t << " PROPERTIES\n";
		os << "    BUILD_RPATH   \"${PYCP_DIST}/lib;$ORIGIN;$ORIGIN/lib\"\n";
		os << "    INSTALL_RPATH \"$ORIGIN;$ORIGIN/lib\"\n";
		os << ")\n";
	}
	if (!mod_shared.empty()) os << "\n";

	// ---- rpath / -rdynamic / 部署：仅在存在动态形态时需要 ----
	// 全静态（runtime static 且无任何 shared 模块/内置扩展）的产物自包含：
	// 不需要 rpath、-rdynamic，也不需要把 stdlib/、lib/ 复制到 exe 同级。
	if (!rt_shared && mod_shared.empty() && spec.builtin_shared.empty()) {
		os << "# 全静态自包含产物：无 DLL、无 rpath、无需运行期部署。\n";
		return os.str();
	}

	// exe rpath：让 exe 在任何目录都能找到同级 lib/ 下的运行时库。
	os << "# rpath：让 exe 在任何目录都能找到同级 lib/ 下的运行时库\n";
	os << "set_target_properties(" << exe << " PROPERTIES\n";
	os << "    BUILD_RPATH   \"${PYCP_DIST}/lib;$ORIGIN/lib;$ORIGIN\"\n";
	os << "    INSTALL_RPATH \"$ORIGIN/lib;$ORIGIN\"\n";
	os << ")\n\n";

	// Linux/macOS：导出主程序符号，使 import 的「进程内符号」查找
	// （dlsym(RTLD_DEFAULT, "PycpModule_xxx")）能命中链接进本程序的模块。
	os << "# Linux/macOS：导出主程序符号，使 import 的「进程内符号」查找\n";
	os << "# （dlsym(RTLD_DEFAULT, \"PycpModule_xxx\")）能命中链接进本程序的模块。\n";
	os << "if(UNIX AND NOT APPLE)\n";
	os << "    target_link_options(" << exe << " PRIVATE -rdynamic)\n";
	os << "endif()\n\n";

	// 运行期部署：import io 等按「exe 同级 stdlib/」查找原生扩展，
	// 且 io.so 自身 rpath 指向 $ORIGIN/../lib，故 lib/ 必须一并复制。
	os << "# 运行期部署：import io 等按「exe 同级 stdlib/」查找原生扩展，\n";
	os << "# 且 io.so 自身 rpath 指向 $ORIGIN/../lib，故 lib/ 必须一并复制。\n";
	os << "add_custom_command(TARGET " << exe << " POST_BUILD\n";
	os << "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
	os << "            \"${PYCP_DIST}/stdlib\" $<TARGET_FILE_DIR:" << exe
	   << ">/stdlib\n";
	os << "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
	os << "            \"${PYCP_DIST}/lib\" $<TARGET_FILE_DIR:" << exe
	   << ">/lib\n";
	os << ")\n\n";

	// Windows：加载 DLL 只搜 exe 同级目录、不搜 lib/，故运行时 DLL 额外放一份。
	// DLL 名随构建 SDK 的编译器而异（MinGW/GNU 带 lib 前缀，MSVC 不带），
	// 故按候选名探测而非硬编码；找不到（纯静态 SDK 无 DLL）时只提示、不失败。
	os << "# Windows：加载 DLL 只搜 exe 同级目录、不搜 lib/，故运行时 DLL 额外放一份。\n";
	os << "# DLL 名随构建 SDK 的编译器而异：MinGW -> libPycpRuntime.dll，MSVC -> PycpRuntime.dll。\n";
	os << "if(WIN32)\n";
	// 候选文件名：SDK 实际产出的名字优先，其后补两种编译器的约定名（去重）。
	std::vector<std::string> dll_candidates;
	if (!sdk.root_dll.empty()) dll_candidates.push_back(base_name(sdk.root_dll));
	for (const char* n : {"libPycpRuntime.dll", "PycpRuntime.dll"}) {
		if (std::find(dll_candidates.begin(), dll_candidates.end(), n) ==
		    dll_candidates.end()) {
			dll_candidates.push_back(n);
		}
	}

	os << "    set(_pycp_runtime_dll \"\")\n";
	os << "    foreach(_pycp_dll_cand";
	for (const std::string& c : dll_candidates) {
		os << " \"" << cmake_escape(c) << "\"";
	}
	os << ")\n";
	os << "        if(EXISTS \"${PYCP_DIST}/${_pycp_dll_cand}\")\n";
	os << "            set(_pycp_runtime_dll \"${PYCP_DIST}/${_pycp_dll_cand}\")\n";
	os << "            break()\n";
	os << "        endif()\n";
	os << "    endforeach()\n";
	// 回退：SDK 根目录没有时，取 lib/ 下那份（Windows 同样不搜 lib/，仍需复制出来）。
	os << "    if(NOT _pycp_runtime_dll)\n";
	os << "        foreach(_pycp_dll_cand \"libPycpRuntime.dll\" \"PycpRuntime.dll\")\n";
	os << "            if(EXISTS \"${PYCP_DIST}/lib/${_pycp_dll_cand}\")\n";
	os << "                set(_pycp_runtime_dll \"${PYCP_DIST}/lib/${_pycp_dll_cand}\")\n";
	os << "                break()\n";
	os << "            endif()\n";
	os << "        endforeach()\n";
	os << "    endif()\n";
	os << "    if(_pycp_runtime_dll)\n";
	os << "        add_custom_command(TARGET " << exe << " POST_BUILD\n";
	os << "            COMMAND ${CMAKE_COMMAND} -E copy_if_different\n";
	os << "                    \"${_pycp_runtime_dll}\" $<TARGET_FILE_DIR:"
	   << exe << ">/\n";
	os << "        )\n";
	os << "    else()\n";
	os << "        message(STATUS \"Pycp: ${PYCP_DIST} 下未找到运行时 DLL"
	      "（纯静态 SDK？），跳过复制到 exe 同级目录。\")\n";
	os << "    endif()\n";
	os << "endif()\n\n";

	// 动态模块 DLL 部署：复制到 exe 同级 stdlib/（运行时按 exe 目录的
	// stdlib/ 查找）。先构建目标再复制，确保文件已生成。
	if (!mod_shared.empty()) {
		os << "# 动态模块 DLL 复制到 exe 同级 stdlib/（运行期按名 dlopen）\n";
		for (const ModuleTarget* mt : mod_shared) {
			const std::string t = module_target(mt->name);
			os << "add_dependencies(" << exe << " " << t << ")\n";
			os << "add_custom_command(TARGET " << exe << " POST_BUILD\n";
			os << "    COMMAND ${CMAKE_COMMAND} -E copy_if_different\n";
			os << "            $<TARGET_FILE:" << t << "> "
			      "$<TARGET_FILE_DIR:" << exe << ">/stdlib/\n";
			os << ")\n";
		}
	}

	return os.str();
}

} // namespace Pycp::AOT
