#include "aot/PycpCMakeGenerator.hpp"

#include "PycpConfig.hpp" // AOT_ENTRY_CPP_FILENAME

#include <algorithm>
#include <sstream>
#include <vector>

namespace Pycp::AOT {

const CMakeGenerator kCMakeGenerator;

// 静态初始化阶段自注册：委托全局实例的地址，确保本生成器纳入注册表。
namespace {
const bool kRegistered = []() {
	RegisterGenerator(&kCMakeGenerator);
	return true;
}();
} // anonymous namespace

namespace {

// 转义，使其在 CMake 字符串字面量中安全（处理反斜杠与引号）。
std::string cmake_escape(const std::string& s) {
	std::string out;
	out.reserve(s.size() + 4);
	for (char c : s) {
		if (c == '\\') out += "\\\\";
		else if (c == '"') out += "\\\"";
		else out += c;
	}
	return out;
}

// 取路径最后一段（文件名）；无分隔符时返回原串。
// 用于把 SdkInfo::root_dll（绝对路径）转成写入 CMake 的候选文件名。
std::string base_name(const std::string& path) {
	const std::size_t pos = path.find_last_of("/\\");
	return (pos == std::string::npos) ? path : path.substr(pos + 1);
}

// 路径安全化：分隔符统一为 '/'，再转义引号。
//
// 必须统一分隔符：写入 CMake 的绝对路径若含 '\'，在 target_link_libraries
// 这类「原样进入 Makefile 链接命令行」的位置会被 make 当成转义符吞掉，
// MinGW 下表现为 ld "cannot find D:DesktopPycpbuild/dist/lib/..."。
// Windows 接受 '/' 作为路径分隔符，故统一后两端都安全。
std::string cmake_path(const std::string& s) {
	std::string out;
	out.reserve(s.size() + 4);
	for (char c : s) {
		if (c == '\\') out += '/';
		else if (c == '"') out += "\\\"";
		else out += c;
	}
	return out;
}

} // anonymous namespace

std::string CMakeGenerator::Generate(const ProjectSpec& spec) const {
	const SdkInfo& sdk = spec.sdk;
	const bool rt_shared = (spec.runtime_link == LinkMode::kShared);
	const std::string& exe = spec.name;

	// 依赖模块按形态分类（入口恒在主程序 exe 内，不在此列）。
	std::vector<const ModuleTarget*> mod_static;
	std::vector<const ModuleTarget*> mod_shared;
	for (const ModuleTarget& mt : spec.modules) {
		if (mt.kind == ModuleKind::kShared) mod_shared.push_back(&mt);
		else mod_static.push_back(&mt);
	}
	// 全部静态模块统一编进一个归档 target：同归档内互相引用可解析
	//（链接器会对单个归档重扫），天然消解静态环，无需 --start-group。
	const std::string static_lib = exe + "_modules";

	std::ostringstream os;

	// 文件头：注明生成来源与版本、关键形态，便于追溯。
	os << "# Generated by Pycp AOT (emit-cpp) v"
	   << cmake_escape(spec.pycp_version) << "\n";
	os << "# Source entry : " << cmake_escape(spec.source_pycp) << "\n";
	os << "# Runtime link : "
	   << (rt_shared ? "shared (libPycpRuntime)" : "static (libPycpRuntime.a)")
	   << "\n";
	os << "# Module kinds : " << (mod_static.empty() ? "none" : "static")
	   << (mod_static.empty() || mod_shared.empty() ? "" : " + ") << mod_shared.size()
	   << " shared module(s)\n";
	os << "# Builtin ext   : " << spec.builtin_static.size()
	   << " static (linked in), " << spec.builtin_shared.size()
	   << " shared (loaded from stdlib/)\n";
	os << "# Do not edit by hand; re-run: pycp --emit-cpp <entry>.pycp\n\n";

	os << "cmake_minimum_required(VERSION 3.15)\n";
	os << "project(" << exe << " LANGUAGES CXX)\n\n";

	// SDK 根目录：生成时写入绝对路径；换机器用 -DPYCP_DIST=<path> 覆盖。
	os << "# Pycp 运行时 SDK 根目录（生成时写入的绝对路径；换机器用 "
	      "-DPYCP_DIST=<path> 覆盖）\n";
	os << "set(PYCP_DIST \"" << cmake_path(sdk.root) << "\" CACHE PATH "
	      "\"Pycp runtime SDK root\")\n\n";

	os << "set(CMAKE_CXX_STANDARD 17)\n";
	os << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
	os << "set(CMAKE_CXX_EXTENSIONS OFF)\n";
	os << "if(NOT CMAKE_BUILD_TYPE)\n";
	os << "    set(CMAKE_BUILD_TYPE Release)\n";
	os << "endif()\n\n";

	// SDK 缺失时给出可操作错误，而非晦涩的 "cannot find -lPycpRuntime"。
	os << "# SDK 缺失时给出可操作的错误，而非晦涩的 \"cannot find -lPycpRuntime\"\n";
	os << "if(NOT EXISTS \"${PYCP_DIST}/include/PycpABI.hpp\")\n";
	os << "    message(FATAL_ERROR\n";
	os << "        \"Pycp SDK not found at: ${PYCP_DIST}\\n\"\n";
	os << "        \"请指定正确的 SDK 路径：cmake -S . -B build "
	      "-DPYCP_DIST=<pycp 的 build/dist>\")\n";
	os << "endif()\n\n";

	// ---- 入口源与辅助源（注册桩等）----
	// 入口 .gen.cpp 固定名（AOT_ENTRY_CPP_FILENAME）；aux 桩编进主程序。
	os << "# 入口模块与辅助源（注册/拉入桩）编进主程序可执行文件\n";
	os << "set(PYCP_ENTRY_SRC \"" << Pycp::AOT_ENTRY_CPP_FILENAME << "\")\n";
	if (spec.aux_sources.empty()) {
		os << "set(PYCP_AUX_SRCS)\n";
	} else {
		os << "set(PYCP_AUX_SRCS\n";
		for (const std::string& a : spec.aux_sources) os << "    " << a << "\n";
		os << ")\n";
	}
	os << "\n";

	// ---- 目标：主程序 ----
	os << "# ---- 主程序（入口模块 + 静态依赖的注册）----\n";
	os << "add_executable(" << exe << " ${PYCP_ENTRY_SRC} ${PYCP_AUX_SRCS})\n\n";

	// ---- 目标：全部静态依赖模块（合并为一个静态库归档）----
	if (!mod_static.empty()) {
		os << "# ---- 静态模块库（kStatic 依赖模块，编进主程序）----\n";
		os << "# 合并为单个归档：同归档内互相引用可解析，无需 --start-group。\n";
		os << "add_library(" << static_lib << " STATIC\n";
		for (const ModuleTarget* mt : mod_static) {
			os << "    " << mt->source_file << "   # " << mt->name << "\n";
		}
		os << ")\n\n";
	}

	// ---- 目标：动态模块（各自一个 DLL/SO，运行期 dlopen）----
	if (!mod_shared.empty()) {
		os << "# ---- 动态模块库（kShared 依赖模块，运行期按名加载）----\n";
		for (const ModuleTarget* mt : mod_shared) {
			const std::string t = "pycp_mod_" + mt->name;
			os << "# " << mt->name << ": " << mt->source_file << "\n";
			os << "add_library(" << t << " SHARED " << mt->source_file << ")\n";
			// 导出名直接取模块名（去掉 CMake 默认 lib 前缀与 target 前缀）：
			// 运行时按 "<name>.so/.dll" 查找（LoadNativeModuleFrom）。
			os << "set_target_properties(" << t << " PROPERTIES\n";
			os << "    OUTPUT_NAME \"" << mt->name << "\"\n";
			os << "    PREFIX \"\"\n";
			os << ")\n";
		}
		os << "\n";
	}

	// ---- 各 target 的 include/link 目录（统一段）----
	auto emit_common_dirs = [&](const std::string& t) {
		os << "target_include_directories(" << t
		   << " PRIVATE \"${PYCP_DIST}/include\")\n";
		os << "target_link_directories(" << t
		   << " PRIVATE \"${PYCP_DIST}/lib\")\n";
	};
	emit_common_dirs(exe);
	if (!mod_static.empty()) emit_common_dirs(static_lib);
	for (const ModuleTarget* mt : mod_shared) {
		emit_common_dirs("pycp_mod_" + mt->name);
	}
	os << "\n";

	// ---- 编译定义 ----
	// 静态运行时（全镜像无 DLL）：所有 TU 取消 __declspec(dllimport)。
	// 动态模块 DLL：定义 PYCP_BUILDING_MODULE 以 dllexport 自身入口。
	if (!rt_shared) {
		os << "target_compile_definitions(" << exe << " PRIVATE PYCP_STATIC)\n";
		if (!mod_static.empty()) {
			os << "target_compile_definitions(" << static_lib
			   << " PRIVATE PYCP_STATIC)\n";
		}
		os << "\n";
	}
	for (const ModuleTarget* mt : mod_shared) {
		os << "target_compile_definitions(pycp_mod_" << mt->name
		   << " PRIVATE PYCP_BUILDING_MODULE)\n";
	}
	if (!mod_shared.empty()) os << "\n";

	// ---- 链接关系 ----
	// 主程序：
	os << "# ---- 链接 ----\n";
	if (!mod_static.empty()) {
		os << "# 主程序直接链接静态模块归档（链接器按符号拉取所需成员）。\n";
	}
	os << "target_link_libraries(" << exe << " PRIVATE\n";
	if (!mod_static.empty()) os << "    " << static_lib << "\n";
	if (rt_shared) {
		// 共享运行时：主程序与 stdlib 扩展统一链接同一份 libPycpRuntime，
		// 保证全进程只有一份运行时状态（GC 池 / 小整数池 / 句柄缓存）。
		os << "    PycpRuntime\n";
	} else {
		os << "    # 静态运行时 + 静态链入的内置扩展（绝对路径，避免 MinGW 选中\n";
		os << "    # 同目录的 DLL 导入库 libPycpRuntime.dll.a）\n";
		os << "    \"" << cmake_path(sdk.static_runtime) << "\"\n";
		for (const std::string& lib : spec.builtin_static_lib_paths) {
			os << "    \"" << cmake_path(lib) << "\"\n";
		}
	}
	os << ")\n\n";

	// 动态模块：链接共享运行时与（必要时）静态模块归档（static 依赖）。
	for (const ModuleTarget* mt : mod_shared) {
		const std::string t = "pycp_mod_" + mt->name;
		os << "target_link_libraries(" << t << " PRIVATE PycpRuntime";
		if (!mod_static.empty()) os << " " << static_lib;
		os << ")\n";
		// DLL 自己的 rpath：运行期需要定位 libPycpRuntime（若部署时放在
		// 别处）以及自身可能的静态依赖（不适用，static 依赖已链入自身）。
		os << "set_target_properties(" << t << " PROPERTIES\n";
		os << "    BUILD_RPATH   \"${PYCP_DIST}/lib;$ORIGIN;$ORIGIN/lib\"\n";
		os << "    INSTALL_RPATH \"$ORIGIN;$ORIGIN/lib\"\n";
		os << ")\n";
	}
	if (!mod_shared.empty()) os << "\n";

	// ---- rpath / -rdynamic / 部署：仅在存在动态形态时需要 ----
	// 全静态（runtime static 且无任何 shared 模块/内置扩展）的产物自包含：
	// 不需要 rpath、-rdynamic，也不需要把 stdlib/、lib/ 复制到 exe 同级。
	if (!rt_shared && mod_shared.empty() && spec.builtin_shared.empty()) {
		os << "# 全静态自包含产物：无 DLL、无 rpath、无需运行期部署。\n";
		return os.str();
	}

	// exe rpath：让 exe 在任何目录都能找到同级 lib/ 下的运行时库。
	os << "# rpath：让 exe 在任何目录都能找到同级 lib/ 下的运行时库\n";
	os << "set_target_properties(" << exe << " PROPERTIES\n";
	os << "    BUILD_RPATH   \"${PYCP_DIST}/lib;$ORIGIN/lib;$ORIGIN\"\n";
	os << "    INSTALL_RPATH \"$ORIGIN/lib;$ORIGIN\"\n";
	os << ")\n\n";

	// Linux/macOS：导出主程序符号，使 import 的「进程内符号」查找
	// （dlsym(RTLD_DEFAULT, "PycpModule_xxx")）能命中链接进本程序的模块。
	os << "# Linux/macOS：导出主程序符号，使 import 的「进程内符号」查找\n";
	os << "# （dlsym(RTLD_DEFAULT, \"PycpModule_xxx\")）能命中链接进本程序的模块。\n";
	os << "if(UNIX AND NOT APPLE)\n";
	os << "    target_link_options(" << exe << " PRIVATE -rdynamic)\n";
	os << "endif()\n\n";

	// 运行期部署：import io 等按「exe 同级 stdlib/」查找原生扩展，
	// 且 io.so 自身 rpath 指向 $ORIGIN/../lib，故 lib/ 必须一并复制。
	os << "# 运行期部署：import io 等按「exe 同级 stdlib/」查找原生扩展，\n";
	os << "# 且 io.so 自身 rpath 指向 $ORIGIN/../lib，故 lib/ 必须一并复制。\n";
	os << "add_custom_command(TARGET " << exe << " POST_BUILD\n";
	os << "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
	os << "            \"${PYCP_DIST}/stdlib\" $<TARGET_FILE_DIR:" << exe
	   << ">/stdlib\n";
	os << "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
	os << "            \"${PYCP_DIST}/lib\" $<TARGET_FILE_DIR:" << exe
	   << ">/lib\n";
	os << ")\n\n";

	// Windows：加载 DLL 只搜 exe 同级目录、不搜 lib/，故运行时 DLL 额外放一份。
	// DLL 名随构建 SDK 的编译器而异（MinGW/GNU 带 lib 前缀，MSVC 不带），
	// 故按候选名探测而非硬编码；找不到（纯静态 SDK 无 DLL）时只提示、不失败。
	os << "# Windows：加载 DLL 只搜 exe 同级目录、不搜 lib/，故运行时 DLL 额外放一份。\n";
	os << "# DLL 名随构建 SDK 的编译器而异：MinGW -> libPycpRuntime.dll，MSVC -> PycpRuntime.dll。\n";
	os << "if(WIN32)\n";
	// 候选文件名：SDK 实际产出的名字优先，其后补两种编译器的约定名（去重）。
	std::vector<std::string> dll_candidates;
	if (!sdk.root_dll.empty()) dll_candidates.push_back(base_name(sdk.root_dll));
	for (const char* n : {"libPycpRuntime.dll", "PycpRuntime.dll"}) {
		if (std::find(dll_candidates.begin(), dll_candidates.end(), n) ==
		    dll_candidates.end()) {
			dll_candidates.push_back(n);
		}
	}

	os << "    set(_pycp_runtime_dll \"\")\n";
	os << "    foreach(_pycp_dll_cand";
	for (const std::string& c : dll_candidates) {
		os << " \"" << cmake_escape(c) << "\"";
	}
	os << ")\n";
	os << "        if(EXISTS \"${PYCP_DIST}/${_pycp_dll_cand}\")\n";
	os << "            set(_pycp_runtime_dll \"${PYCP_DIST}/${_pycp_dll_cand}\")\n";
	os << "            break()\n";
	os << "        endif()\n";
	os << "    endforeach()\n";
	// 回退：SDK 根目录没有时，取 lib/ 下那份（Windows 同样不搜 lib/，仍需复制出来）。
	os << "    if(NOT _pycp_runtime_dll)\n";
	os << "        foreach(_pycp_dll_cand \"libPycpRuntime.dll\" \"PycpRuntime.dll\")\n";
	os << "            if(EXISTS \"${PYCP_DIST}/lib/${_pycp_dll_cand}\")\n";
	os << "                set(_pycp_runtime_dll \"${PYCP_DIST}/lib/${_pycp_dll_cand}\")\n";
	os << "                break()\n";
	os << "            endif()\n";
	os << "        endforeach()\n";
	os << "    endif()\n";
	os << "    if(_pycp_runtime_dll)\n";
	os << "        add_custom_command(TARGET " << exe << " POST_BUILD\n";
	os << "            COMMAND ${CMAKE_COMMAND} -E copy_if_different\n";
	os << "                    \"${_pycp_runtime_dll}\" $<TARGET_FILE_DIR:"
	   << exe << ">/\n";
	os << "        )\n";
	os << "    else()\n";
	os << "        message(STATUS \"Pycp: ${PYCP_DIST} 下未找到运行时 DLL"
	      "（纯静态 SDK？），跳过复制到 exe 同级目录。\")\n";
	os << "    endif()\n";
	os << "endif()\n\n";

	// 动态模块 DLL 部署：复制到 exe 同级 stdlib/（运行时按 exe 目录的
	// stdlib/ 查找）。先构建目标再复制，确保文件已生成。
	if (!mod_shared.empty()) {
		os << "# 动态模块 DLL 复制到 exe 同级 stdlib/（运行期按名 dlopen）\n";
		for (const ModuleTarget* mt : mod_shared) {
			const std::string t = "pycp_mod_" + mt->name;
			os << "add_dependencies(" << exe << " " << t << ")\n";
			os << "add_custom_command(TARGET " << exe << " POST_BUILD\n";
			os << "    COMMAND ${CMAKE_COMMAND} -E copy_if_different\n";
			os << "            $<TARGET_FILE:" << t << "> "
			      "$<TARGET_FILE_DIR:" << exe << ">/stdlib/\n";
			os << ")\n";
		}
	}

	return os.str();
}

} // namespace Pycp::AOT
