#include "PycpAot.hpp"

#include <fstream>
#include <sstream>
#include <stdexcept>

namespace Pycp::AOT {

// =============================================================
// AOT 骨架实现
//
// 当前返回一段可直接编译的 .cpp 骨架：
//   - 包含 PycpABI.hpp
//   - 在 main() 中 Pycp::Initialize / Finalize
//   - 以注释形式标注字节码 IR 的注入位置（常量池 / 指令流）
//
// 后续实现时，将在此处把 module.const_pool 翻译为常量构造代码、
// 把 module.code_objects 的指令流翻译为顺序调用的 ABI 调用序列。
// =============================================================

std::string EmitCpp(const Pycp::BC::Module& module,
                    const std::string& entry_name) {
	std::ostringstream os;

	os << "// =====================================================\n";
	os << "// Auto-generated by Pycp AOT compiler (skeleton).\n";
	os << "// Do not edit manually.\n";
	os << "// =====================================================\n\n";

	os << "#include \"PycpABI.hpp\"\n";
	os << "#include <cstdio>\n\n";

	os << "// ---- 常量池（" << module.const_pool.size() << " 项）----\n";
	os << "// TODO: 将 module.const_pool 翻译为 Integer_FromLong / String_FromString 调用\n";
	os << "//       并 GC_AddRoot 保护。\n\n";

	os << "// ---- 符号表（" << module.symtab.size() << " 项）----\n";
	os << "// TODO: 符号表索引在编译期内联为整数常量，无需运行时字符串表。\n\n";

	os << "// ---- 代码对象（" << module.code_objects.size() << " 个）----\n";
	os << "// TODO: 将每个 CodeObject 的指令流翻译为顺序执行的 ABI 调用序列。\n\n";

	os << "int " << entry_name << "() {\n";
	os << "    Pycp::Initialize();\n";
	os << "    // TODO: 执行生成的字节码指令序列\n";
	os << "    Pycp::Finalize();\n";
	os << "    return 0;\n";
	os << "}\n\n";

	os << "int main() {\n";
	os << "    return " << entry_name << "();\n";
	os << "}\n";

	return os.str();
}

bool EmitCppToFile(const Pycp::BC::Module& module, const std::string& path) {
	std::string src = EmitCpp(module);
	std::ofstream f(path, std::ios::binary);
	if (!f) return false;
	f << src;
	return f.good();
}

} // namespace Pycp::AOT
